# Generated by Django 6.1 on 2026-08-19 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_contactmessage_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=420)),
                ('content', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=160)),
                ('cover_image', models.FileField(blank=True, upload_to='crypto/events/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kripto događaj',
                'verbose_name_plural': 'Kripto događaji',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='CryptoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Početni'), ('intermediate', 'Srednji'), ('advanced', 'Napredni')], default='beginner', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kripto lekcija',
                'verbose_name_plural': 'Kripto lekcije',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CryptoEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='crypto/events/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.cryptoevent')),
            ],
            options={
                'verbose_name': 'Slika događaja',
                'verbose_name_plural': 'Slike događaja',
                'ordering': ['order', 'id'],
            },
        ),
    ]
