# Generated by Django 6.1 on 2026-08-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_adminemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(help_text='Primjer: /ai-automatizacija', max_length=180, unique=True, verbose_name='URL putanja')),
                ('page_name', models.CharField(max_length=120, verbose_name='Naziv stranice')),
                ('title_bs', models.CharField(max_length=180, verbose_name='SEO naslov — BS')),
                ('description_bs', models.TextField(max_length=320, verbose_name='Meta opis — BS')),
                ('title_en', models.CharField(blank=True, max_length=180, verbose_name='SEO naslov — EN')),
                ('description_en', models.TextField(blank=True, max_length=320, verbose_name='Meta opis — EN')),
                ('title_de', models.CharField(blank=True, max_length=180, verbose_name='SEO naslov — DE')),
                ('description_de', models.TextField(blank=True, max_length=320, verbose_name='Meta opis — DE')),
                ('primary_keyword', models.CharField(blank=True, max_length=180, verbose_name='Primarni keyword')),
                ('secondary_keywords', models.TextField(blank=True, help_text='Jedan keyword po redu ili odvojeni zarezom.', verbose_name='Sekundarni keywordi')),
                ('search_intent', models.CharField(choices=[('commercial', 'Komercijalna'), ('local', 'Lokalna'), ('informational', 'Informativna'), ('transactional', 'Transakcijska'), ('navigational', 'Navigacijska')], default='commercial', max_length=20, verbose_name='Search intent')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=180, verbose_name='Open Graph naslov')),
                ('og_description', models.TextField(blank=True, max_length=320, verbose_name='Open Graph opis')),
                ('og_image', models.URLField(blank=True, verbose_name='Open Graph slika')),
                ('schema_type', models.CharField(choices=[('WebPage', 'Web stranica'), ('Service', 'Usluga'), ('ContactPage', 'Kontakt'), ('CollectionPage', 'Kolekcija'), ('AboutPage', 'O nama')], default='WebPage', max_length=40, verbose_name='Schema tip')),
                ('is_indexed', models.BooleanField(default=True, verbose_name='Dozvoli indeksiranje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO stranica',
                'verbose_name_plural': 'SEO Manager',
                'ordering': ['route'],
            },
        ),
    ]
