# Generated by Django 6.1 on 2026-08-26 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_update_contact_seo_positioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('excerpt', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'Općenito'), ('crypto', 'Kripto i Web3'), ('marketing', 'Marketing'), ('software', 'Softver'), ('ai', 'AI automatizacija'), ('consulting', 'Konsulting')], default='general', max_length=20)),
                ('cover_logo', models.CharField(choices=[('binance', 'Binance'), ('solana', 'Solana'), ('gordondm', 'GordonDM')], default='gordondm', max_length=20)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog članak',
                'verbose_name_plural': 'Blogovi',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
