# Generated by Django 6.1 on 2026-08-27 09:06

from django.db import migrations

def expand_blog_content(apps, schema_editor):
    BlogPost = apps.get_model('website', 'BlogPost')
    updates = {
        'gordondm-binance-saradnja': {
            'excerpt': 'Saradnja GordonDM-a i Binance ekosistema usmjerena je na događaje, edukaciju i jačanje svijesti o odgovornoj primjeni kripta u Sarajevu i na Balkanu.',
            'content': 'GordonDM i Binance potpisali su ugovor o saradnji usmjeren na razvoj zajedničkih inicijativa, razmjenu znanja i promociju odgovorne primjene blockchain tehnologije u Bosni i Hercegovini i širem regionu Balkana.\n\nVažan dio saradnje odnosi se na organizaciju događaja, edukativnih susreta i otvorenih razgovora u Sarajevu. Cilj je približiti kripto i Web3 teme ljudima koji žele razumjeti tehnologiju, ali i kompanijama koje istražuju njenu praktičnu poslovnu primjenu.\n\nKroz konferencije, radionice i lokalna okupljanja planirano je povezivanje domaće zajednice sa stručnjacima i predstavnicima blockchain ekosistema koji djeluju na Balkanu. Fokus neće biti samo na promociji kripta, nego i na sigurnosti, odgovornom upravljanju digitalnom imovinom i jasnom razumijevanju rizika.\n\nSaradnja otvara prostor i za kvalitetnije predstavljanje blockchain projekata, marketinške kampanje prilagođene regionalnom tržištu te podršku događajima koji okupljaju developere, poduzetnike, kompanije i nove korisnike. Sarajevo u tom procesu ima potencijal postati važna tačka povezivanja tehnoloških ideja i regionalne Web3 zajednice.\n\nGordonDM će kroz svoje iskustvo u digitalnom marketingu, razvoju softvera, organizaciji sadržaja i lokalnom tržištu doprinositi tome da se globalne kripto teme prevedu u razumljive i korisne inicijative za ljude i kompanije na Balkanu. Konkretni događaji i aktivnosti bit će predstavljeni kroz naredne objave.',
        },
        'gordondm-solana-saradnja': {
            'excerpt': 'Saradnja GordonDM-a i Solana ekosistema povezuje događaje, edukaciju i razvoj praktičnih blockchain inicijativa u Sarajevu i širom Balkana.',
            'content': 'GordonDM i Solana potpisali su ugovor o saradnji s fokusom na edukaciju, razvoj blockchain rješenja i povezivanje poslovnih ideja s modernom Web3 infrastrukturom. Poseban naglasak stavljen je na Sarajevo i mogućnosti koje lokalna tehnološka zajednica može ponuditi regionalnom tržištu.\n\nPlanirana saradnja uključuje događaje, radionice, prezentacije i sadržaje koji Solana tehnologiju približavaju developerima, startupima, kompanijama i ljudima koji tek ulaze u svijet kripta. Ideja je pokazati gdje blockchain ima stvarnu primjenu, a gdje je potrebno dodatno znanje, testiranje i odgovoran pristup.\n\nKroz povezivanje s ljudima i zajednicama aktivnim u Solana ekosistemu na Balkanu, GordonDM želi pomoći razvoju regionalne mreže u kojoj se mogu razmjenjivati iskustva, predstavljati projekti i pokretati nove saradnje. Sarajevo može biti mjesto susreta lokalnih talenata, regionalnih partnera i međunarodnih Web3 inicijativa.\n\nSaradnja obuhvata i promociju događaja, digitalne kampanje, kvalitetniji edukativni sadržaj i komunikaciju koja kompleksne blockchain teme pretvara u razumljive poruke. Time se kripto ne predstavlja samo kao tržište digitalne imovine, nego kao infrastruktura za proizvode, zajednice i nove poslovne modele.\n\nU narednom periodu fokus će biti na inicijativama koje mogu ojačati svijest o sigurnoj i korisnoj primjeni Web3 tehnologije, podržati regionalne developere i otvoriti prostor za projekte razvijene u Bosni i Hercegovini. Detalji događaja i konkretnih aktivnosti bit će objavljivani kroz GordonDM blog i društvene kanale.',
        },
    }
    for slug, values in updates.items():
        BlogPost.objects.filter(slug=slug).update(**values)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_seed_partnership_blogs'),
    ]

    operations = [
        migrations.RunPython(expand_blog_content, migrations.RunPython.noop),
    ]
