# Generated by Django 6.1 on 2026-08-27 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_expand_partnership_blog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-id'], 'verbose_name': 'Blog članak'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='blog/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='blog/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.blogpost')),
            ],
            options={
                'verbose_name': 'Slika bloga',
                'verbose_name_plural': 'Galerija bloga',
                'ordering': ['order', 'id'],
            },
        ),
    ]
