# Generated by Django 6.1 on 2026-08-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_seed_binance_campus_budva'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_de',
            field=models.TextField(blank=True, verbose_name='Sadržaj — DE'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Sadržaj — EN'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_de',
            field=models.TextField(blank=True, max_length=500, verbose_name='Kratki opis — DE'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='Kratki opis — EN'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(blank=True, max_length=220, verbose_name='Naslov — DE'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=220, verbose_name='Naslov — EN'),
        ),
    ]
