# Generated by Django 6.1 on 2026-09-08 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_expand_short_blog_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsVisit',
            fields=[
                ('token', models.UUIDField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_path', models.CharField(max_length=250)),
                ('device', models.CharField(max_length=20)),
                ('source', models.CharField(default='direct', max_length=120)),
                ('campaign', models.CharField(blank=True, max_length=100)),
                ('placement', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nepoznato', max_length=80)),
                ('city', models.CharField(default='Nepoznato', max_length=100)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Analitička sesija',
                'verbose_name_plural': 'Analitičke sesije',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('token', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(db_index=True, max_length=30)),
                ('path', models.CharField(max_length=250)),
                ('target', models.CharField(blank=True, max_length=250)),
                ('seconds', models.PositiveSmallIntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.analyticsvisit')),
            ],
        ),
    ]
