# Generated by Django 6.1 on 2026-09-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_workproject_roles_worktask_parent_workattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='appearance',
            field=models.JSONField(default=dict),
        ),
    ]
