# Generated by Django 6.1 on 2026-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_worktask_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminemail',
            name='mailbox',
            field=models.CharField(db_index=True, default='primary', max_length=40),
        ),
        migrations.AlterField(
            model_name='adminemail',
            name='uid',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='adminemail',
            constraint=models.UniqueConstraint(fields=('mailbox', 'uid'), name='unique_mailbox_uid'),
        ),
    ]
