# Generated by Django 6.1 on 2026-09-14 13:22

from django.db import migrations, models


def mark_existing_team(apps, schema_editor):
    apps.get_model('website','WorkProject').objects.filter(pk='e6f3350e-d093-48ae-b583-50810d328917').update(team_visible=True)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_workchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workproject',
            name='team_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_team, migrations.RunPython.noop),
    ]
