# Generated by Django 6.1 on 2026-09-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_workproject_team_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='workproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
